### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jwamsterdam** [bendrucker/parse-google-autocomplete#1]
The following will give me an map undefined error.. 

```
let response = parse([{'description':'Rembrandtplein, Amster'}])
console.log(response)
```

any solution?

**Comment by bendrucker** [comment]
Is it really possible to get just that response back? Just description and no other properties?

**Comment by jwamsterdam** [comment]
ok, but then I really dont understand the readme, Will continue reading, but my goal is to populate a dropdown beneath an input field. Hope that is one of the purposes of your package?

**Comment by bendrucker** [comment]
The idea is to parse the types of responses that Google provides to build something like a formatted autocomplete list:

https://github.com/bendrucker/parse-google-autocomplete/blob/master/fixtures

It doesn't look to me like Google would send that back but if you have proof they do I can reconsider.
